// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARxoQ8652qhSh4gMqv34EiCd3mF0ee7R4',
    appId: '1:975201092112:web:cc38ca8d816994d2614095',
    messagingSenderId: '975201092112',
    projectId: 'authentic-wave',
    authDomain: 'authentic-wave.firebaseapp.com',
    storageBucket: 'authentic-wave.firebasestorage.app',
    measurementId: 'G-4CYWPQL7XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALfnTa0YTbAeRyciV2QBJYRqgCYzKhvnQ',
    appId: '1:975201092112:android:c67fa2fcc8e63bb6614095',
    messagingSenderId: '975201092112',
    projectId: 'authentic-wave',
    storageBucket: 'authentic-wave.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCquJlA7rjswZcNlK_rctK8QlNB-mpnWMg',
    appId: '1:975201092112:ios:518b7acf71d05525614095',
    messagingSenderId: '975201092112',
    projectId: 'authentic-wave',
    storageBucket: 'authentic-wave.firebasestorage.app',
    iosBundleId: 'com.example.authDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCquJlA7rjswZcNlK_rctK8QlNB-mpnWMg',
    appId: '1:975201092112:ios:518b7acf71d05525614095',
    messagingSenderId: '975201092112',
    projectId: 'authentic-wave',
    storageBucket: 'authentic-wave.firebasestorage.app',
    iosBundleId: 'com.example.authDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARxoQ8652qhSh4gMqv34EiCd3mF0ee7R4',
    appId: '1:975201092112:web:89b35ac323398296614095',
    messagingSenderId: '975201092112',
    projectId: 'authentic-wave',
    authDomain: 'authentic-wave.firebaseapp.com',
    storageBucket: 'authentic-wave.firebasestorage.app',
    measurementId: 'G-N79M5K18HD',
  );
}
